apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 687690439986.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 687690439986.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: ad9b9907
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
